package com.diamond.future.utility;

import android.app.Activity;
import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.drawable.ColorDrawable;
import android.os.Environment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.Window;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.appcompat.app.AlertDialog;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class UtilNew {
    public static final String APP_DIRECTORY = "future";
    public static String getItemDir() {
        File dirReports = new File(Environment.getExternalStorageDirectory(),
                UtilNew.APP_DIRECTORY);
        if (!dirReports.exists()) {
            if (!dirReports.mkdirs()) {
                return null;
            }
        }
        return dirReports.getAbsolutePath();
    }

    public static Map<String, String> getCountryCodeDictionary() {
        Map<String, String> countryCodeDictionary = new HashMap<>();
        countryCodeDictionary.put("IL", "972");
        countryCodeDictionary.put("AF", "93");
        countryCodeDictionary.put("AL", "355");
        countryCodeDictionary.put("DZ", "213");
        countryCodeDictionary.put("AS", "1");
        countryCodeDictionary.put("AD", "376");
        countryCodeDictionary.put("AO", "244");
        countryCodeDictionary.put("AI", "1");
        countryCodeDictionary.put("AG", "1");
        countryCodeDictionary.put("AR", "54");
        countryCodeDictionary.put("AM", "374");
        countryCodeDictionary.put("AW", "297");
        countryCodeDictionary.put("AU", "61");
        countryCodeDictionary.put("AT", "43");
        countryCodeDictionary.put("AZ", "994");
        countryCodeDictionary.put("BS", "1");
        countryCodeDictionary.put("BH", "973");
        countryCodeDictionary.put("BD", "880");
        countryCodeDictionary.put("BB", "1");
        countryCodeDictionary.put("BY", "375");
        countryCodeDictionary.put("BE", "32");
        countryCodeDictionary.put("BZ", "501");
        countryCodeDictionary.put("BJ", "229");
        countryCodeDictionary.put("BM", "1");
        countryCodeDictionary.put("BT", "975");
        countryCodeDictionary.put("BA", "387");
        countryCodeDictionary.put("BW", "267");
        countryCodeDictionary.put("BR", "55");
        countryCodeDictionary.put("IO", "246");
        countryCodeDictionary.put("BG", "359");
        countryCodeDictionary.put("BF", "226");
        countryCodeDictionary.put("BI", "257");
        countryCodeDictionary.put("KH", "855");
        countryCodeDictionary.put("CM", "237");
        countryCodeDictionary.put("CA", "1");
        countryCodeDictionary.put("CV", "238");
        countryCodeDictionary.put("KY", "345");
        countryCodeDictionary.put("CF", "236");
        countryCodeDictionary.put("TD", "235");
        countryCodeDictionary.put("CL", "56");
        countryCodeDictionary.put("CN", "86");
        countryCodeDictionary.put("CX", "61");
        countryCodeDictionary.put("CO", "57");
        countryCodeDictionary.put("KM", "269");
        countryCodeDictionary.put("CG", "242");
        countryCodeDictionary.put("CK", "682");
        countryCodeDictionary.put("CR", "506");
        countryCodeDictionary.put("HR", "385");
        countryCodeDictionary.put("CU", "53");
        countryCodeDictionary.put("CY", "537");
        countryCodeDictionary.put("CZ", "420");
        countryCodeDictionary.put("DK", "45");
        countryCodeDictionary.put("DJ", "253");
        countryCodeDictionary.put("DM", "1");
        countryCodeDictionary.put("DO", "1");
        countryCodeDictionary.put("EC", "593");
        countryCodeDictionary.put("EG", "20");
        countryCodeDictionary.put("SV", "503");
        countryCodeDictionary.put("GQ", "240");
        countryCodeDictionary.put("ER", "291");
        countryCodeDictionary.put("EE", "372");
        countryCodeDictionary.put("ET", "251");
        countryCodeDictionary.put("FO", "298");
        countryCodeDictionary.put("FJ", "679");
        countryCodeDictionary.put("FI", "358");
        countryCodeDictionary.put("FR", "33");
        countryCodeDictionary.put("GF", "594");
        countryCodeDictionary.put("PF", "689");
        countryCodeDictionary.put("GA", "241");
        countryCodeDictionary.put("GM", "220");
        countryCodeDictionary.put("GE", "995");
        countryCodeDictionary.put("DE", "49");
        countryCodeDictionary.put("GH", "233");
        countryCodeDictionary.put("GI", "350");
        countryCodeDictionary.put("GR", "30");
        countryCodeDictionary.put("GL", "299");
        countryCodeDictionary.put("GD", "1");
        countryCodeDictionary.put("GP", "590");
        countryCodeDictionary.put("GU", "1");
        countryCodeDictionary.put("GT", "502");
        countryCodeDictionary.put("GN", "224");
        countryCodeDictionary.put("GW", "245");
        countryCodeDictionary.put("GY", "595");
        countryCodeDictionary.put("HT", "509");
        countryCodeDictionary.put("HN", "504");
        countryCodeDictionary.put("HU", "36");
        countryCodeDictionary.put("IS", "354");
        countryCodeDictionary.put("IN", "91");
        countryCodeDictionary.put("ID", "62");
        countryCodeDictionary.put("IQ", "964");
        countryCodeDictionary.put("IE", "353");
        countryCodeDictionary.put("IT", "39");
        countryCodeDictionary.put("JM", "1");
        countryCodeDictionary.put("JP", "81");
        countryCodeDictionary.put("JO", "962");
        countryCodeDictionary.put("KZ", "77");
        countryCodeDictionary.put("KE", "254");
        countryCodeDictionary.put("KI", "686");
        countryCodeDictionary.put("KW", "965");
        countryCodeDictionary.put("KG", "996");
        countryCodeDictionary.put("LV", "371");
        countryCodeDictionary.put("LB", "961");
        countryCodeDictionary.put("LS", "266");
        countryCodeDictionary.put("LR", "231");
        countryCodeDictionary.put("LI", "423");
        countryCodeDictionary.put("LT", "370");
        countryCodeDictionary.put("LU", "352");
        countryCodeDictionary.put("MG", "261");
        countryCodeDictionary.put("MW", "265");
        countryCodeDictionary.put("MY", "60");
        countryCodeDictionary.put("MV", "960");
        countryCodeDictionary.put("ML", "223");
        countryCodeDictionary.put("MT", "356");
        countryCodeDictionary.put("MH", "692");
        countryCodeDictionary.put("MQ", "596");
        countryCodeDictionary.put("MR", "222");
        countryCodeDictionary.put("MU", "230");
        countryCodeDictionary.put("YT", "262");
        countryCodeDictionary.put("MX", "52");
        countryCodeDictionary.put("MC", "377");
        countryCodeDictionary.put("MN", "976");
        countryCodeDictionary.put("ME", "382");
        countryCodeDictionary.put("MS", "1");
        countryCodeDictionary.put("MA", "212");
        countryCodeDictionary.put("MM", "95");
        countryCodeDictionary.put("NA", "264");
        countryCodeDictionary.put("NR", "674");
        countryCodeDictionary.put("NP", "977");
        countryCodeDictionary.put("NL", "31");
        countryCodeDictionary.put("AN", "599");
        countryCodeDictionary.put("NC", "687");
        countryCodeDictionary.put("NZ", "64");
        countryCodeDictionary.put("NI", "505");
        countryCodeDictionary.put("NE", "227");
        countryCodeDictionary.put("NG", "234");
        countryCodeDictionary.put("NU", "683");
        countryCodeDictionary.put("NF", "672");
        countryCodeDictionary.put("MP", "1");
        countryCodeDictionary.put("NO", "47");
        countryCodeDictionary.put("OM", "968");
        countryCodeDictionary.put("PK", "92");
        countryCodeDictionary.put("PW", "680");
        countryCodeDictionary.put("PA", "507");
        countryCodeDictionary.put("PG", "675");
        countryCodeDictionary.put("PY", "595");
        countryCodeDictionary.put("PE", "51");
        countryCodeDictionary.put("PH", "63");
        countryCodeDictionary.put("PL", "48");
        countryCodeDictionary.put("PT", "351");
        countryCodeDictionary.put("PR", "1");
        countryCodeDictionary.put("QA", "974");
        countryCodeDictionary.put("RO", "40");
        countryCodeDictionary.put("RW", "250");
        countryCodeDictionary.put("WS", "685");
        countryCodeDictionary.put("SM", "378");
        countryCodeDictionary.put("SA", "966");
        countryCodeDictionary.put("SN", "221");
        countryCodeDictionary.put("RS", "381");
        countryCodeDictionary.put("SC", "248");
        countryCodeDictionary.put("SL", "232");
        countryCodeDictionary.put("SG", "65");
        countryCodeDictionary.put("SK", "421");
        countryCodeDictionary.put("SI", "386");
        countryCodeDictionary.put("SB", "677");
        countryCodeDictionary.put("ZA", "27");
        countryCodeDictionary.put("GS", "500");
        countryCodeDictionary.put("ES", "34");
        countryCodeDictionary.put("LK", "94");
        countryCodeDictionary.put("SD", "249");
        countryCodeDictionary.put("SR", "597");
        countryCodeDictionary.put("SZ", "268");
        countryCodeDictionary.put("SE", "46");
        countryCodeDictionary.put("CH", "41");
        countryCodeDictionary.put("TJ", "992");
        countryCodeDictionary.put("TH", "66");
        countryCodeDictionary.put("TG", "228");
        countryCodeDictionary.put("TK", "690");
        countryCodeDictionary.put("TO", "676");
        countryCodeDictionary.put("TT", "1");
        countryCodeDictionary.put("TN", "216");
        countryCodeDictionary.put("TR", "90");
        countryCodeDictionary.put("TM", "993");
        countryCodeDictionary.put("TC", "1");
        countryCodeDictionary.put("TV", "688");
        countryCodeDictionary.put("UG", "256");
        countryCodeDictionary.put("UA", "380");
        countryCodeDictionary.put("AE", "971");
        countryCodeDictionary.put("GB", "44");
        countryCodeDictionary.put("US", "1");
        countryCodeDictionary.put("UY", "598");
        countryCodeDictionary.put("UZ", "998");
        countryCodeDictionary.put("VU", "678");
        countryCodeDictionary.put("WF", "681");
        countryCodeDictionary.put("YE", "967");
        countryCodeDictionary.put("ZM", "260");
        countryCodeDictionary.put("ZW", "263");
        countryCodeDictionary.put("BO", "591");
        countryCodeDictionary.put("BN", "673");
        countryCodeDictionary.put("CC", "61");
        countryCodeDictionary.put("CD", "243");
        countryCodeDictionary.put("CI", "225");
        countryCodeDictionary.put("FK", "500");
        countryCodeDictionary.put("GG", "44");
        countryCodeDictionary.put("VA", "379");
        countryCodeDictionary.put("HK", "852");
        countryCodeDictionary.put("IR", "98");
        countryCodeDictionary.put("IM", "44");
        countryCodeDictionary.put("JE", "44");
        countryCodeDictionary.put("KP", "850");
        countryCodeDictionary.put("KR", "82");
        countryCodeDictionary.put("LA", "856");
        countryCodeDictionary.put("LY", "218");
        countryCodeDictionary.put("MO", "853");
        countryCodeDictionary.put("MK", "389");
        countryCodeDictionary.put("FM", "691");
        countryCodeDictionary.put("MD", "373");
        countryCodeDictionary.put("MZ", "258");
        countryCodeDictionary.put("PS", "970");
        countryCodeDictionary.put("PN", "872");
        countryCodeDictionary.put("RE", "262");
        countryCodeDictionary.put("RU", "7");
        countryCodeDictionary.put("BL", "590");
        countryCodeDictionary.put("SH", "290");
        countryCodeDictionary.put("KN", "1");
        countryCodeDictionary.put("LC", "1");
        countryCodeDictionary.put("MF", "590");
        countryCodeDictionary.put("PM", "508");
        countryCodeDictionary.put("VC", "1");
        countryCodeDictionary.put("ST", "239");
        countryCodeDictionary.put("SO", "252");
        countryCodeDictionary.put("SJ", "47");
        countryCodeDictionary.put("SY", "963");
        countryCodeDictionary.put("TW", "886");
        countryCodeDictionary.put("TZ", "255");
        countryCodeDictionary.put("TL", "670");
        countryCodeDictionary.put("VE", "58");
        countryCodeDictionary.put("VN", "84");
        countryCodeDictionary.put("VG", "1");
        countryCodeDictionary.put("VI", "1");

        return countryCodeDictionary;
    }
    public static boolean hasCountryCode(String phoneNumber) {
        // Define a regular expression for a phone number with country code
        // This regex assumes that a country code starts with '+' and is followed by one or more digits
        String countryCodeRegex = "^\\+\\d+";
        // Create a Pattern object
        Pattern pattern = Pattern.compile(countryCodeRegex);
        // Create a Matcher object
        Matcher matcher = pattern.matcher(phoneNumber);
        // Check if the pattern matches the input phone number
        return matcher.find();
    }
}
